// ══════════════════════════════════════════════════════════════════
// Site content as data. All apps read from here.
// Essay bodies are 'TODO' placeholders — filled in by the essay agent.
// ══════════════════════════════════════════════════════════════════

export const META = {
  name: 'Ethan Yip',
  tagline: 'Builder · Researcher · Investor',
  role: 'Chief of Staff, Engineering & Technology at Resonance',
  location: 'New York',
  focus: 'Emotional intelligence for humanoid agents · Mechanistic interpretability',
};

export const BIO = [
  'Started coding games at 9. By 12, I was teaching CS to 50+ kids at my middle school. At 15, I flew into SF alone with no plan and scaled from zero to a team of 7 in a month.',
  'I grew up chasing the things I couldn’t find, and building them when they didn’t exist yet.',
  'Outside the work, I read philosophy, keep up my Latin, and write essays — usually about the things that keep me up at night. Philosophy is the lens I bring to everything.',
];

// A statement used for flavor in whoami / about.
export const STATEMENT = {
  quote:
    'The next paradigm in technology is emotional. And those who see it early are going to look wrong for a while.',
  attribution: 'Ethan Yip, 2026',
};

export const NOW = [
  { org: 'Resonance', what: 'Chief of Staff, Engineering & Technology', when: '2026', href: 'https://rsnc.ai' },
  { org: 'Substrate Labs', what: 'Research — Mechanistic Interpretability', when: '2026', href: 'https://substrate-labs.org' },
  { org: 'HTSI Global', what: 'Director — Founder Ecosystems', when: '2025', href: null },
  { org: 'United Nations', what: 'Youth Delegate — ECOSOC', when: '2025', href: null },
  { org: 'LvlUp Ventures', what: 'VC in Residence — AI & Software', when: '2025', href: null },
  { org: 'Amazon Web Services', what: 'Machine Learning — Former', when: '2026', href: null },
];

export const PAPERS = [
  {
    no: '01',
    year: '2026',
    role: 'Primary Author',
    title: 'PRISM: Predicting and Repairing Instability in SAE Manifolds',
    desc: "Uses sparse-autoencoder boundary proximity to predict which prompts will destabilize a model's internal geometry before any answer is produced — then rewrites them to recover the lost accuracy.",
    tags: ['Sparse Autoencoders', 'Interpretability', 'Gemma Scope', 'Prompt Geometry'],
  },
  {
    no: '02',
    year: '2026',
    role: 'Coauthor',
    title: 'Shadow: Geometric Characterization of LLM Reasoning Manifolds',
    desc: 'Activation-steering work applying Forman–Ricci curvature to the FFN-output manifolds of Mistral-7B, probing the geometric structure of reasoning through cross-layer graphs and Bayesian analysis.',
    tags: ['PyTorch', 'Interpretability', 'Bayesian Networks', 'Mistral-7B'],
  },
  {
    no: '03',
    year: '2025',
    role: 'Primary Author',
    title: 'Temporal Aggregation for Transformer-Based Depression Detection',
    desc: 'Shows that how text is structured for training — independent of model architecture — materially shifts transformer-based depression classification performance.',
    tags: ['DepRoBERTa', 'Temporal Aggregation', 'Reddit Corpus', 'Mental-Health NLP'],
  },
];

export const ESSAYS = [
  {
    no: '01',
    slug: 'faultlines',
    title: 'Fault Lines',
    desc: 'What Toto Wolff and Mercedes get structurally right about blame, accountability, and high-performance culture — and how SF gets it backwards.',
    eyebrow: 'The Hidden Curriculum of Leadership · Essay 1',
    date: 'June 2026',
    body: [
      { type: 'eyebrow', text: 'The Hidden Curriculum of Leadership · Essay 1' },
      { type: 'p', html: "In 2016, Lewis Hamilton and Nico Rosberg, Mercedes' two championship drivers, collided on the opening lap of the Spanish Grand Prix at Barcelona, retiring both cars on the spot. In a single corner, forty-three championship points, millions of dollars, and months of preparation had all just evaporated in under a minute." },
      { type: 'p', html: 'The instinct, from all of us watching from the outside, was incredibly obvious: to find out whose fault it was.' },
      { type: 'p', html: 'What Toto Wolff did next is one of the most important things any leader can do when something goes catastrophically wrong.' },
      { type: 'img', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Ricciardo_Verstappen_Vettel_Spain_2016.jpg/1920px-Ricciardo_Verstappen_Vettel_Spain_2016.jpg', alt: 'Ricciardo, Verstappen and Vettel fighting for the lead at the 2016 Spanish Grand Prix', caption: 'With both Mercedes cars retired, Verstappen went on to take his first-ever F1 win at just 18. Photo: Alex Rushton / CC BY 2.0' },
      { type: 'h2', marker: 'I', text: 'The first story is about blame.' },
      { type: 'p', html: 'There\'s a <a href="https://www.youtube.com/watch?v=q8mGymE7bXo" target="_blank" rel="noopener noreferrer">video from the Mercedes Deep Dive series</a> where Toto Wolff, Team Principal and CEO of Mercedes AMG Petronas, walks through his entire leadership philosophy: his no blame culture, purpose, and leading by example. To this day it is one of my favorite leadership conversations I have come across, for how honest and unfiltered it is, coming from someone running one of the most dominant dynasties in sports history.' },
      { type: 'img', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Toto_Wolff_at_the_Melbourne_Walk_during_the_2026_Australian_Grand_Prix_%28028A8425%29.jpg/960px-Toto_Wolff_at_the_Melbourne_Walk_during_the_2026_Australian_Grand_Prix_%28028A8425%29.jpg', alt: 'Toto Wolff at the 2026 Australian Grand Prix Melbourne Walk', caption: 'Toto Wolff, Mercedes AMG Petronas Team Principal. Photo: Yu Chu Chin / CC BY-SA 4.0' },
      { type: 'p', html: 'His argument is deceptively simple. When something breaks, it is fundamentally on you as the leader. Not the mechanic. Not the engineer. Not the driver. If a wheel gun malfunctions, the process that allowed it to malfunction is the problem, and that process is yours to design and own. We blame the process, not the person. He has said it in interview after interview. The fact that he keeps saying it probably tells you everything.' },
      { type: 'p', html: 'Harvard Business School professor Anita Elberse spent time embedded with the Mercedes team in 2021, watching them operate before, during, and after races. Her <a href="https://hbr.org/2022/11/number-one-in-formula-one" target="_blank" rel="noopener noreferrer">research, published in the Harvard Business Review</a> and now part of HBS curriculum, found that this philosophy was one of the central pillars holding the dynasty together. This is not a system you reach for after something breaks. It has to work even when everything is going right. That is what makes it hard, and that is what made Mercedes different.' },
      { type: 'p', html: 'The logic underneath it is identical to something aviation figured out decades ago. In Crew Resource Management, the framework that reshaped how airlines think about safety, catastrophic failure almost never comes from one person\'s mistake. It comes from a chain of small system errors that nobody felt safe enough to surface. The no-blame culture is what keeps that chain from forming.' },
      { type: 'pull', text: 'A hidden error in a high-risk system is exponentially more dangerous than an acknowledged one.' },
      { type: 'h2', marker: 'II', text: 'The second story is about the aftermath of the crash.' },
      { type: 'p', html: 'When Niki Lauda, Mercedes\' non-executive chairman and a three-time world champion, walked out of that garage in Barcelona, he did what most people\'s instincts told them to do.' },
      { type: 'p', html: 'He immediately went on camera and publicly blamed Hamilton.' },
      { type: 'p', html: 'Wolff\'s response was different. When reporters pointed out that Lauda had identified Hamilton as the culprit, Wolff <a href="https://africa.espn.com/f1/story/_/id/15549526/toto-wolff-lewis-hamilton-nico-rosberg-collision-not-clear-cut" target="_blank" rel="noopener noreferrer">pushed back directly</a>: <em>"Niki has from his driver\'s perspective, he has an opinion and this is his instinct and it\'s fair enough that he has that — but if you look at the data and when you have the discussions with the drivers it\'s maybe different. It\'s not clear cut."</em>' },
      { type: 'pull', text: "Protect the driver. Look at the data. Don't let instinct substitute for analysis." },
      { type: 'p', html: 'But accountability absolutely still followed. It was deliberate, structural, and it landed hard on the systems and agreements behind the drivers, not just that moment itself.' },
      { type: 'p', html: 'Both drivers were fined. Mercedes split the <a href="https://www.gpfans.com/en/f1-news/1070002/f1-nico-rosberg-mercedes-fine-lewis-hamilton-incident-2026-spanish-gp-barcelona/" target="_blank" rel="noopener noreferrer">£360,000 repair bill between Hamilton and Rosberg equally</a> along with a contract both had to sign acknowledging that their actions had consequences. Lauda was explicit: "We have to win, one of you guys has to win, you cannot push each other off." Contract clauses were inserted with the threat of termination if it happened again. And James Vowles, then Mercedes\' head of strategy, created what became known internally as the <a href="https://www.formula1.com/en/latest/article/vowles-shares-details-of-secret-document-mercedes-used-to-manage-intense.4FzNhDoTm7T3Rxdk3Sm1QT" target="_blank" rel="noopener noreferrer">Rules of Engagement</a>: a formal document that codified on-track behavior between teammates and set the parameters for how they would compete going forward.' },
      { type: 'callout', html: '<strong>Blame and accountability.</strong> These are not the same thing, and Mercedes ran both simultaneously.' },
      { type: 'p', html: 'Most leaders collapse these two things. Blame is finding a person to carry the fault. Accountability is understanding what actually broke, and making sure the system is built so it doesn\'t break the same way again. Blame feels like accountability because it\'s fast, it\'s satisfying, and it gives the fault somewhere to land. Real accountability is slower and harder, and it requires you to look back very critically at the things that you built.' },
      { type: 'p', html: 'Take the no-blame principle too far and you get an organization where nothing is anyone\'s responsibility, and performance quietly deteriorates because consequences never land. Take blame culture too far and you get a team too afraid to surface problems, where errors stay hidden until they become catastrophic. Mercedes steered the narrow road between them.' },
      { type: 'h2', marker: 'III', text: 'The third story is about the fact that Toto Wolff is a human being.' },
      { type: 'p', html: "Because he is, and it's probably the most important part of all this." },
      { type: 'img', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Susie_Wolff%2C_Niki_Lauda%2C_Toto_Wolff.jpg/1920px-Susie_Wolff%2C_Niki_Lauda%2C_Toto_Wolff.jpg', alt: 'Susie Wolff, Niki Lauda, and Toto Wolff on stage at a Mercedes event', caption: 'Susie Wolff, Niki Lauda, and Toto Wolff at a Mercedes motorsport event, Stuttgart 2014. When Lauda blamed Hamilton publicly, Wolff pushed back. Photo: Thomas Ormston / CC BY 2.0' },
      { type: 'p', html: 'In 2016, after Hamilton and Rosberg collided again at the Austrian Grand Prix, there was visible frustration from the garage. In 2021, during the Saudi Arabian Grand Prix, as the Hamilton–Verstappen rivalry reached its most volatile point, cameras caught Wolff screaming at his monitor and throwing his headset across the desk. Later that season at Abu Dhabi, as Hamilton lost the championship on the final lap under circumstances Wolff still describes as incomprehensible, his radio produced the now-legendary "No Mikey No... that was so not right" directed at race director Michael Masi, a line that has not left F1 fan culture since. The emotions were all over his face in real time, and he\'s said he thinks about that race every day.' },
      { type: 'p', html: 'In 2023, when Mercedes produced the W14, a car that managed to be simultaneously complicated, inconsistent, and painfully slow, Wolff <a href="https://www.gpfans.com/en/f1-news/107138/toto-wolff-mercedes-f1-car-w14-2023-not-acceptable-nasty-piece-of-work-miami-grand-prix/" target="_blank" rel="noopener noreferrer">called it "not acceptable" and "a nasty piece of work"</a> and said at one point the car simply didn\'t deserve to win. Notably, the blame went to the car and the system, not to Hamilton, not to Russell. But you cannot deny or pretend that the anger or emotion wasn\'t there.' },
      { type: 'p', html: 'This is important because the no-blame culture is sometimes discussed as though it requires leaders to be emotionally flat: to process disasters with some kind of detached calm. Toto Wolff is not emotionally flat. He feels the losses hard and doesn\'t always hide it. What the no-blame culture actually requires isn\'t the absence of emotion. It\'s the discipline to not let emotion drive the diagnosis.' },
      { type: 'pull', text: 'You can be furious at the situation. The question is whether you then spend that energy finding a person or finding the problem.' },
      { type: 'h2', marker: 'IV', text: 'What this produces in people.' },
      { type: 'p', html: 'Lewis Hamilton arrived at Mercedes in 2013, having spent his entire life inside the McLaren ecosystem from junior karting through his first six Formula 1 seasons. He described the difference plainly years later: at McLaren, the engineers largely believed they knew best and didn\'t always make space for driver input. At Mercedes, <a href="https://www.essentiallysports.com/f1-news-lewis-hamilton-reveals-one-of-the-biggest-difference-between-mclaren-and-mercedes/" target="_blank" rel="noopener noreferrer">the dynamic was built around genuine collaboration</a> and the driver was treated as a core part of the engineering process, not an output of it.' },
      { type: 'img', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Lewis_Hamilton-Mercedes_W11_%285%29.jpg/960px-Lewis_Hamilton-Mercedes_W11_%285%29.jpg', alt: 'Lewis Hamilton in Mercedes W11 at Circuit de Barcelona-Catalunya testing, 2020', caption: 'Hamilton in the W11 at Barcelona, 2020, the car that won his seventh championship. Photo: Alberto-g-rovi / CC BY 3.0' },
      { type: 'p', html: 'James Vowles, who watched Hamilton closely throughout his Mercedes years, <a href="https://www.planetf1.com/news/lewis-hamilton-mentality-shift-mercedes" target="_blank" rel="noopener noreferrer">observed a real shift in mentality</a>: from "win every race at all costs, full stop" to something more nuanced. Maximizing results as part of a system, trusting the people around him, giving and receiving feedback in ways that compound over time.' },
      { type: 'p', html: "Optimize for the process, not the result. That's longevity." },
      { type: 'p', html: 'Six of his seven championships came in that environment.' },
      { type: 'p', html: 'We all watched Hamilton cross over to Ferrari in 2025. <a href="https://www.formula1.com/en/latest/article/i-hold-no-grudge-wolff-on-hamiltons-ferrari-move-how-he-was-told-and-the.1cATzXmouKYAF9TtytvlTZ" target="_blank" rel="noopener noreferrer">Wolff said publicly he held no grudge</a>. He talked about it the way you\'d want any partnership to end: nothing but warmth for the person, even after the work was done. After the 2026 Chinese Grand Prix in Shanghai, Hamilton stepped off the podium in a Ferrari race suit and boarded Toto\'s private jet alongside Valtteri Bottas and George Russell. Three current and former Mercedes drivers, all Mercedes family. Bono, Hamilton\'s longtime race engineer, was there on the podium celebrating with all of them. You don\'t get that from a blame culture.' },
      { type: 'h2', text: 'Why does this matter to you as a leader, startup founder, or investor?' },
      { type: 'p', html: 'If you have spent any time in the startup world, and specifically in the engineering founder culture of San Francisco and New York, you have seen the opposite system at work. I\'m not naming specific accelerators, VCs or companies; there is a pattern I have seen enough times to give it a name: the talent formula. Take founders at completely different stages, with completely different backgrounds, run them all through an identical roadmap with identical metrics, and measure success by identical outputs.' },
      { type: 'p', html: 'I had a conversation with <a href="https://www.linkedin.com/in/heejin-irene-koo" target="_blank" rel="noopener noreferrer">Irene Koo</a>, partner at Soma Capital, that touched on exactly this: the rigidity of systems, and what happens when the framework starts serving itself instead of the people it was built to develop. The mold becomes the point. And when a startup fails inside that mold, the fault almost always lands on the founder, their execution, their commitment, their ability to fit the shape. Rarely on the system that was supposed to support them.' },
      { type: 'p', html: 'I have sat across from a 13-year-old founder pitching VCs at a United Nations and HTSI event, and thought, genuinely, that this person might be remarkable someday. Not because of their traction. Because of how they thought about the problem. The moment we, as people of empowerment, measure that person by exclusively startup metrics instead of by who they are becoming, we have already drawn the fault line in exactly the wrong spot.' },
      { type: 'h2', text: 'The final story is about San Francisco, and getting it wrong.' },
      { type: 'p', html: 'A few years ago I was working on a startup, fast-moving, operating across different cities, the kind of thing where the hustle felt personal (because it really was). Growth rates were churning. Deliverables were high. Demand was slow. Something was very evidently wrong.' },
      { type: 'p', html: 'My first instinct was to find the person.' },
      { type: 'p', html: 'There was a team member I pushed blame toward, and as the leader of the organization, I watched the rest of my team pile blame onto them too. I did it the way that feels like decisiveness: fast, critical, direct, and specific. What I thought was accountability was actually relief. The fault line had somewhere to go that wasn\'t back toward the go-to-market strategy we\'d designed, the expectations we\'d set, or the gaps in how we\'d built the system.' },
      { type: 'p', html: 'I was wrong. The fault was inherently in the system, and most importantly, it was the system that <em>I</em> designed. By the time I understood that, the team had already changed. The dynamic had shifted, and relationships built through real hustle across cities were quietly different than before. We stayed on good terms. But different is a cost that doesn\'t show up on any dashboard.' },
      { type: 'p', html: 'Around the same period I was working with a group of interns and developers at Constellation Technologies, people from universities, professionals, some who had recently come to the US following the displacement in Ukraine. I made a point of showing up to the smaller meetings, of writing cover letters for people moving on to their next opportunity, of giving people a real view into the work. Not because I had to, but because I genuinely believed that what you put into the development of people compounds. The founders who understand that early build better teams. The teams that feel genuinely invested in build better products. The causality runs in one direction, and it starts with how you treat the people inside your system.' },
      { type: 'p', html: 'I think about this now when I look at how HTSI\'s programs get evaluated. It is easy to measure a young founder by their startup\'s traction. That is the very same talent formula operating in disguise. When things don\'t work, the fault almost never lives in the founder. It lives in how the system around them was built and where the pressure was placed. As a startup founder, you need to adopt the same mentality toward the people inside your own organization.' },
      { type: 'hr' },
      { type: 'p', html: 'Toto Wolff is not a case study in emotional perfection. The headset had been thrown (multiple times). Abu Dhabi 2021 still very much lives within him. The key idea I urge us to come back to is that none of that undoes the structural thing he did get right: when something broke, he looked at the system before he looked for a person. That is easier said than done, of course, but that\'s one of the best approaches to take when things go very wrong.' },
      { type: 'p', html: 'You won\'t get it right every time. Neither did he. But the discipline of asking "what in the system produced this outcome" before asking "who caused this problem" is one of the most important things I have seen genuinely change how organizations operate over time.' },
      { type: 'p', html: "That's where we should draw the fault line." },
    ],
    sources: [
      { label: 'Mercedes Deep Dive: Toto Wolff on no-blame culture and leadership', href: 'https://www.youtube.com/watch?v=q8mGymE7bXo' },
      { label: 'HBR: Anita Elberse on leadership lessons from Mercedes F1', href: 'https://hbr.org/2022/11/number-one-in-formula-one' },
      { label: 'Wolff on Spain 2016: "not clear cut"', href: 'https://africa.espn.com/f1/story/_/id/15549526/toto-wolff-lewis-hamilton-nico-rosberg-collision-not-clear-cut' },
      { label: 'Lauda on Hamilton: "unacceptable"', href: 'https://africa.espn.com/f1/story/_/id/15549400/niki-lauda-blames-lewis-hamilton-unacceptable-nico-rosberg-collision' },
      { label: 'The £360k fine and the Rules of Engagement', href: 'https://www.gpfans.com/en/f1-news/1070002/f1-nico-rosberg-mercedes-fine-lewis-hamilton-incident-2026-spanish-gp-barcelona/' },
      { label: 'Vowles on the Rules of Engagement document', href: 'https://www.formula1.com/en/latest/article/vowles-shares-details-of-secret-document-mercedes-used-to-manage-intense.4FzNhDoTm7T3Rxdk3Sm1QT' },
      { label: 'Toto on the W14: "not acceptable, nasty piece of work"', href: 'https://www.gpfans.com/en/f1-news/107138/toto-wolff-mercedes-f1-car-w14-2023-not-acceptable-nasty-piece-of-work-miami-grand-prix/' },
      { label: "Toto's headset moment, 2021 Saudi Arabia", href: 'https://www.si.com/onsi/f1/news/f1-news-toto-wolff-comments-on-his-headphone-fury-ive-broken-a-few' },
      { label: 'Hamilton on McLaren vs Mercedes culture', href: 'https://www.essentiallysports.com/f1-news-lewis-hamilton-reveals-one-of-the-biggest-difference-between-mclaren-and-mercedes/' },
      { label: 'Hamilton mentality shift at Mercedes: James Vowles', href: 'https://www.planetf1.com/news/lewis-hamilton-mentality-shift-mercedes' },
      { label: 'Toto on Hamilton\'s Ferrari move: "I hold no grudge"', href: 'https://www.formula1.com/en/latest/article/i-hold-no-grudge-wolff-on-hamiltons-ferrari-move-how-he-was-told-and-the.1cATzXmouKYAF9TtytvlTZ' },
      { label: 'Mercedes Junior Programme history', href: 'https://mercedes-f1.shorthandstories.com/a-history-of-the-mercedes-f1-junior-programme/' },
      { label: 'Gwen Lagrue and scouting Antonelli', href: 'https://www.planetf1.com/features/mercedes-gwen-lagrue-discovering-george-russell-and-kimi-antonelli' },
      { label: '2026 Mercedes Junior Programme announcement', href: 'https://www.mercedesamgf1.com/news/introducing-our-2026-junior-driver-line-up' },
    ],
  },
  {
    no: '02',
    slug: 'byinvitationonly',
    title: 'By Invitation Only',
    desc: 'Why the most talent-dense teams — from Anthropic to the United Nations — are built the exact opposite of open, meritocratic hiring.',
    eyebrow: 'The Hidden Curriculum of Leadership · Essay 2',
    date: 'June 2026',
    body: [
      { type: 'eyebrow', text: 'The Hidden Curriculum of Leadership · Essay 2' },
      { type: 'p', html: 'The startup world is deeply in love with the word "meritocracy". You must find the best talent, open applications, blind reviews. We\'ve built entire systems around the idea that great teams can only be assembled via fair and open process. That\'s absolutely how you build a great team.' },
      { type: 'p', html: 'And yet, every <em>exceptional</em> team was built the exact opposite way. Closed networks, warm introductions, and very deliberate decisions about who gets near the vision. The invitation was never open. The filter was and always will be there. The only question is whether you ran it on purpose or not.' },
      { type: 'p', html: 'This essay is about the invitation: what it actually is, and what the right people do to the rooms they walk into. Every time I have watched someone try to fix a broken one, it has already been too little too late.' },
      { type: 'img', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/San_Francisco_from_the_Marin_Headlands_in_March_2019.jpg/1920px-San_Francisco_from_the_Marin_Headlands_in_March_2019.jpg', alt: 'San Francisco from the Marin Headlands, March 2019', caption: 'San Francisco from the Marin Headlands. The city that runs the invitation harder than anywhere else in the world. Photo: King of Hearts / CC BY-SA 4.0' },
      { type: 'h2', marker: 'I', text: 'The first story is about what an invitation actually is.' },
      { type: 'p', html: 'Hiring is usually talked about as a transaction. You give someone a salary, they give you a function, and the whole thing is bounded and replaceable on both sides.' },
      { type: 'p', html: 'The best early team decisions I have seen weren\'t transactions. They felt more like declarations. Someone looked at another person and made a call that was never truly about the role at all. I think that difference matters more than most hiring frameworks acknowledge, and it carries something a contract doesn\'t.' },
      { type: 'p', html: 'This is what elite universities are actually selling, and it is almost never the curriculum. The room is the product. Put enough people operating at high standards together and those standards become ambient. You stop feeling like you are pushing and start feeling like things just naturally work that way. I have watched this happen in classrooms and I have watched it happen in early teams. The natural environment will do more work than the culture you try to artificially induce.' },
      { type: 'p', html: 'The same thing runs through old money circles, through the networks that move serious capital, through rooms I have only recently had the chance to observe. People cluster not just because of shared taste but because the room shapes what is visible. What risks feel possible, what timescale feels normal. The invitation is into a way of seeing, not just a seat at the table.' },
      { type: 'img', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Naval_Ravikant_in_2011.jpg/960px-Naval_Ravikant_in_2011.jpg', alt: 'Naval Ravikant at Startup School 2011', caption: 'Naval Ravikant at Startup School, 2011. Photo: Steve Jurvetson / CC BY-SA 2.0' },
      { type: 'p', html: 'One of my favorite quotes of all time is Naval Ravikant\'s: <em>play long-term games with long-term people.</em> Good things take time. The only people who stay long enough for good things to materialize are the ones who accepted a declaration, not a deal. Short term players optimize for the next move. Long term players optimize for what compounds. That distinction begins with the invitation.' },
      { type: 'h2', marker: 'II', text: 'The second story is about what A players do to the room.' },
      { type: 'img', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Ben_Horowitz_at_TechCrunch_Disrupt.jpg/960px-Ben_Horowitz_at_TechCrunch_Disrupt.jpg', alt: 'Ben Horowitz at TechCrunch Disrupt', caption: 'Ben Horowitz at TechCrunch Disrupt. Photo: TechCrunch / CC BY 2.0' },
      { type: 'p', html: 'Ben Horowitz in <a href="https://a16z.com/books/the-hard-thing-about-hard-things/" target="_blank" rel="noopener noreferrer">The Hard Thing About Hard Things</a> makes the argument that most startup founders need to hear: hire for the right kind of ambition, people who want the company to succeed and see their own success as a byproduct of that. Hire for genuine strengths, not for lack of weaknesses. Set a high standard and defend it actively. It is the right framework, and I think there is something worth adding to it.' },
      { type: 'p', html: 'The most important part about A players is not just about what they do in a room, but what they do <em>to</em> the room.' },
      { type: 'p', html: 'Different problems become visible. Different things start feeling unacceptable. In an interview with HBS professor Anita Elberse, Toto Wolff said that finishing third or fourth was not just a learning moment. It was a defeat, and it should be treated as such. That standard did not live in a document. It lived in the people. The moment the room changes, the standard changes with it. Not officially, but perceptually, and usually before anyone has named what just happened.' },
      { type: 'p', html: 'I have personally caught myself doing this, and I think it\'s a broader human thing: we calibrate to the people around us and quietly shift our expectations to protect ourselves. <a href="https://en.wikipedia.org/wiki/Asch_conformity_experiments" target="_blank" rel="noopener noreferrer">Asch\'s conformity experiments</a> showed it in a lab. You\'ll see it in your team. Either the bar stays high and people execute there, or the room slowly sinks into the abyss.' },
      { type: 'p', html: 'Agency, standards, vision, culture. These are the traits that matter in A players, and what I have come to think is that you don\'t find them by screening for them. You write an invitation clear enough that people who already carry those things can recognize themselves in it.' },
      { type: 'p', html: 'Look at the density of talent at Anthropic right now. That did not happen because they ran better interviews. It happened because the mission was written specifically enough that a certain kind of person felt it was addressed to them personally. A vague invitation attracts vague people, not because the candidates are wrong, but because the game wasn\'t made specific enough for the right ones to see themselves in it.' },
      { type: 'p', html: 'A credential tells you someone performed well inside a system that already existed. Character is what you need when the system doesn\'t exist yet. Both matter, but they are not the same thing, and the invitation you write will signal which one you are actually screening for.' },
      { type: 'p', html: 'Steven Bartlett hired someone with a two-line CV and zero experience because she thanked the security guard by name on the way into the building. That said more about the room he was building at Flightstory than it did about the hire herself.' },
      { type: 'pull', text: "He wasn't dismissing the credential. He was reading the character." },
      { type: 'h2', marker: 'III', text: 'The third story is about what B players do to the room.' },
      { type: 'p', html: 'B players are not just people who underperform. For me, that is a convenient yet incomplete way to think about it.' },
      { type: 'p', html: 'B players change the room the same way A players do, just in the other direction. Standards that felt fixed start to feel negotiable. Problems that an A player would have surfaced in week one go unnamed for months. The things that made the room exceptional begin to feel like too much rather than just normal, and over time the people around them start adjusting down to meet the new ambient level. It is just how environments work. The room wins, eventually.' },
      { type: 'p', html: 'This is what Bartlett means when he says one bad apple can spoil the bunch, and it is also what makes those first ten hires so consequential. You are not just hiring people. You are setting the environmental conditions that everyone who comes after them will be shaped by without realizing it.' },
      { type: 'p', html: 'The encouraging part is that B players in a room of A players can actually become A players themselves. Put someone in an environment where the standard is high enough and the environment does a lot of the lifting. Elite institutions have known this for a long time. The classroom is the product.' },
      { type: 'p', html: 'None of this is a character judgment on anyone. Sometimes the person you\'re calling a B player just sees the problem differently, and that perspective is worth having in the room. The issue isn\'t the individual. It\'s what happens when too many people without shared alignment start shaping the environment together. At that point it stops being a diversity of perspective and starts being a drift in direction, and nobody can quite explain how you got there.' },
      { type: 'h2', marker: 'IV', text: "What the invitation cannot filter if it's wrong." },
      { type: 'p', html: 'There are only so many believers, and the hard part isn\'t finding them. It is that in an interview, genuine belief and a good performance of belief look almost identical. A vague invitation can\'t tell the difference. It just selects for people who perform belief well enough to get through the room.' },
      { type: 'p', html: 'Believers and paid executors aren\'t different performance tiers. They are people playing different games on different timescales. A believer is building toward an end state. A paid executor is building toward the next deliverable. Those two orientations can produce identical behavior for months before the divergence surfaces.' },
      { type: 'p', html: 'The motive misread is the version of this that founders almost never catch in time. It doesn\'t show up in output. It shows up in direction — in what someone prioritizes when no one is watching, in what they get excited about between formal conversations. You rarely know which one you got in the meeting itself.' },
      { type: 'pull', text: 'You learn more in the ten minutes after a meeting than in the meeting itself.' },
      { type: 'p', html: 'Jason Xu and Ruoyu Xu at Resonance, cousins who have been building together since elementary school, are an extreme version of what aligned timescales look like at the founding level. Not because of the family relationship, but because decades of shared history means the game between them is probably settled before anyone sits down. <a href="https://hbr.org/2013/12/the-founders-dilemma" target="_blank" rel="noopener noreferrer">Noam Wasserman at Harvard found that 65% of high-potential startups fail from co-founder conflict.</a> Most of that is two people who accepted different invitations to the same thing and never surfaced the divergence before it cost them everything.' },
      { type: 'h2', text: 'Why does this matter to you as a leader, founder, or investor?' },
      { type: 'p', html: 'Every team is already, in one way or another, by invitation only. The meritocracy story is more comfortable and easier to put in a pitch deck, but merit still has to get into the room to matter. Who gets evaluated, by what standard, and in front of whom are all questions about the invitation before they\'re questions about merit. The filter is always running, on whatever criteria you established, on purpose or not.' },
      { type: 'p', html: 'A vague invitation produces a vague team. A transactional one produces a team that leaves when the transaction stops making sense. A declaration that says clearly what you are building, for how long, and at what standard produces the thing that actually grows. And the people who accept that kind of invitation tend to leave the room different from how they found it.' },
      { type: 'p', html: 'At HTSI I think about this more than almost anything else. It is easy to let people in on enthusiasm, on what someone says they believe when you are watching. It is much harder to build an invitation specific enough that the right people recognize themselves in it and the wrong ones quietly don\'t. I don\'t think we have fully figured that out yet. But it is probably the most important thing to get right.' },
      { type: 'h2', text: 'The final story is about a startup, and getting this wrong.' },
      { type: 'p', html: '2 years ago I was working on a fast-moving startup, operating across different cities, the kind of thing where growth was entirely reliant on network effects, which meant you had to keep the velocity up just to maintain the slope. There was a genuine product. There were actual users. And at some point, without me noticing, something in the room changed.' },
      { type: 'p', html: 'The mismatch was almost invisible at first. Nothing explicitly wrong was being done. What surfaced slowly was a difference in direction: expanding a free user base as wide as possible versus protecting the roughly two hundred users who were driving most of the revenue. Both are legitimate strategies. But they belong to different games. One builds toward a fundraising story, toward acquisition metrics, toward the kind of growth that looks good in a deck. The other builds toward the users who notice when the product starts to feel like it was built for someone else.' },
      { type: 'p', html: 'What I didn\'t expect was where the first sign came from. It didn\'t come from inside the team. It came from the users. The devoted ones sensed the shift before we had named it internally. They felt the product changing timescale and started leaving. The room\'s perception had already moved. Our conversations just hadn\'t caught up yet.' },
      { type: 'p', html: 'Nothing the other person did was wrong in isolation. But it was misaligned with what I saw, and with what the users were depending on. And that misalignment changed how the users experienced us, which is a cost that almost never makes it onto a post-mortem analysis.' },
      { type: 'callout', html: 'There are not truly many bad hires. There are <strong>incorrect hires</strong>, and the difference matters. The wrong hire is not about the person. It is a mirror of the invitation that let them in. Fix the invitation.' },
      { type: 'p', html: 'If the same misread keeps happening with different faces, you haven\'t written the invitation specific enough about the game you are playing.<br/><br/>Good things take time. Naval\'s line keeps coming back to me: <em>play long-term games with long-term people.</em> Long-term people need an invitation that was never truly about the role.<br/><br/>The best rooms that you have watched, that you are entering, and that you will build are all constructed in the same way:<br/><br/>By Invitation Only.' },
    ],
    sources: [
      { label: 'Ben Horowitz, The Hard Thing About Hard Things', href: 'https://a16z.com/books/the-hard-thing-about-hard-things/' },
      { label: 'Marc Andreessen: Guide to Startups, Part 4 — Hiring', href: 'https://pmarchive.com/guide_to_startups_part4.html' },
      { label: 'Toto Wolff at Harvard Business School on maintaining standards', href: 'https://www.mercedesamgf1.com/news/toto-wolff-to-teach-in-harvard-business-schools-mba-program' },
      { label: 'HBR: Anita Elberse on Mercedes leadership lessons', href: 'https://hbr.org/2022/11/number-one-in-formula-one' },
      { label: 'Steven Bartlett on the first ten people and company culture', href: 'https://www.youtube.com/watch?v=HlfjCtXe9lU' },
      { label: 'Naval Ravikant on long term games with long term people', href: 'https://nav.al/long-term' },
      { label: "Noam Wasserman, The Founder's Dilemma, on co-founder conflict", href: 'https://hbr.org/2013/12/the-founders-dilemma' },
    ],
  },
  {
    no: '03',
    slug: 'ultimateoutsideinsider',
    title: 'The Ultimate Outside Insider',
    desc: 'Why every founder in SF starts to sound the same, and the discipline that protects the position worth holding.',
    eyebrow: 'The Hidden Curriculum of Leadership · Essay 3',
    date: 'June 2026',
    body: [
      { type: 'eyebrow', text: 'The Hidden Curriculum of Leadership · Essay 3' },
      { type: 'p', html: 'The startup world has a phrase it delivers to every founder who is just getting started. Learn by building. Ship it now. Build and iterate faster. Get in the market before you are ready.' },
      { type: 'p', html: 'This is all true. But crucially, they all leave out the same thing.' },
      { type: 'p', html: 'Walk into any room of founders and they will sound remarkably similar. Same vocabulary, same mental models, same frameworks. Walk into a room of VCs and the pattern repeats. This is not a coincidence. Most of them read the same playbooks and learned the game the same way. <a href="https://en.wikipedia.org/wiki/James_Dyson" target="_blank" rel="noopener noreferrer">James Dyson</a> said it plainly: <em>be different for the sake of being different.</em> Because the person who starts from the same place as everyone else ends up in the same place.' },
      { type: 'p', html: 'What never makes it into "learn by building" is the sequence. The people who actually changed the games they entered almost never started with the rulebook.' },
      { type: 'p', html: 'This essay is about the outside insider, and how they play the game.' },
      { type: 'img', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/James_Dyson_4.jpg/1280px-James_Dyson_4.jpg', alt: 'James Dyson at a product presentation', caption: 'James Dyson. The engineer who built 5,127 prototypes before getting the vacuum right — and made that number the brand. Photo: Michiel Hendryckx / CC BY-SA 3.0' },
      { type: 'h2', marker: 'I', text: 'The first story is about trying the game.' },
      { type: 'p', html: 'I remember my first real software engineering experience. It was nothing fancy. This was a time before ChatGPT, Cursor, Claude Code. I was manually building websites by hand and trying to figure out how to center a div and make it blue on Stack Overflow. Truly, the good old days.' },
      { type: 'p', html: 'I didn\'t know it then, but I had some incredible mentors around me. Jason, who went to M&T and then founded Resonance. Max, who went to Duke and then Kalshi. Daniel, who also went to Penn and then Photon. Agni. Daniel Achacon. And so many others I am not mentioning here. I was doing the work, but something was not totally right for me yet. I didn\'t have the vocabulary to fully process what I was watching.' },
      { type: 'p', html: 'What I noticed first was not the technical skill. Don\'t misunderstand. These people were incredibly technical. What I was watching was how they moved in rooms. How they talked to each other when something went wrong. How they decided what to push and when to let something go. How they could read a situation before it had fully resolved itself.' },
      { type: 'p', html: 'I remember Daniel telling me something along the lines of: "cut the corporate jargon, nobody is going to get fired, just tell me what is going on." None of this was in any document I had access to. It was just a result of being in the room with people operating at a frequency I wasn\'t resonating at yet.' },
      { type: 'p', html: 'Then I tried to replicate it. Star Hack, 2023: an international coalition and ranking system for hackathon participants, designed to be financeable and scalable in a space that was slightly less saturated than it is now. Built on everything I had absorbed from those rooms. It did not work. Not because the idea was structurally wrong, but because watching someone play a game and playing it yourself are completely different kinds of knowledge. The rulebook I was trying to follow was the one I had assembled in my head from observation, and it turned out to be full of gaps I had not found yet.' },
      { type: 'p', html: 'Brian Armstrong, CEO of Coinbase, has a line he credits to Paul Graham: <a href="https://tim.blog/2021/03/08/brian-armstrong/" target="_blank" rel="noopener noreferrer">action produces information.</a> If you do not know what to do, just do something, because the doing will tell you what to do next. He said it was true at Coinbase: sometimes he shipped something and the moment it went live, he knew it was wrong. But that gave him the idea for what to do next.' },
      { type: 'img', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Brian_Armstrong_-_TechCrunch_Disrupt_2018_02.jpg/960px-Brian_Armstrong_-_TechCrunch_Disrupt_2018_02.jpg', alt: 'Brian Armstrong at TechCrunch Disrupt 2018', caption: 'Brian Armstrong, CEO of Coinbase, at TechCrunch Disrupt 2018. Photo: TechCrunch / CC BY 2.0' },
      { type: 'pull', text: 'Playing without the rulebook does not just produce information. It produces different information than playing with it.' },
      { type: 'p', html: 'The person who enters a game without the manual asks questions that the manual has already answered for everyone else. They notice structural realities that veterans have long since explained away. They find the edges of the game that the conventional approach has been trained to skip past. Star Hack failing fast was not a waste. It was my first data. The gaps between what I expected and what actually happened were the most valuable thing I had collected since those rooms.' },
      { type: 'p', html: 'The opportunity when you play before you know the rules: you get to learn the game unlike anyone who played it with the rulebook first. Do not waste it.' },
      { type: 'h2', marker: 'II', text: 'The second story is about learning the game.' },
      { type: 'p', html: 'Most people who play the game without the rulebook eventually get the rulebook and stop there. They fold the early lessons into the conventional framework and move forward. That is also leaving something out.' },
      { type: 'p', html: '<a href="https://paulgraham.com/think.html" target="_blank" rel="noopener noreferrer">Paul Graham\'s argument in How to Think for Yourself</a> is specific: some kinds of work can only be done well by people who think differently from everyone else. Scientists, investors, and founders cannot win by being right about what everyone else is already right about. They have to be right about something that most people are currently wrong about. And the problem with full immersion in a game is that the game starts teaching you what to think. The inside insider loses the angle that made them dangerous. The independent-mindedness that was the source of every real insight gets gradually replaced by fluency in the existing frameworks.' },
      { type: 'img', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Paul_Graham_programming.jpg/960px-Paul_Graham_programming.jpg', alt: 'Paul Graham programming at a laptop', caption: 'Paul Graham, co-founder of Y Combinator. His essay How to Think for Yourself is one of the clearest articulations of why the outside insider position matters. Photo: Gabor Cselle / CC BY 2.0' },
      { type: 'p', html: 'This is where the outside insider position matters, and why it has to be built deliberately rather than stumbled into.' },
      { type: 'p', html: 'Not a pure insider. Not captured by the assumptions of the game, not fluent enough in its orthodoxy to mistake the map for the territory. But not a pure outsider either. You still need actual access. Actual information. You need to develop an understanding of what the other side of the table is evaluating before you walk into the room.' },
      { type: 'p', html: 'For me, this looked like learning venture from the startup side. Understanding term sheets and round structure and bridge financing and the logic of financial viability through conversation, through study, and through proximity to people already inside the game. I still am nowhere near knowing it fully. I just know enough of the macro to hold both sides of the table in mind simultaneously.' },
      { type: 'pull', text: 'The outside insider learns the rules in order to understand why what they found without them actually matters.' },
      { type: 'h2', marker: 'III', text: 'The third story is about coming back to the game.' },
      { type: 'p', html: '<a href="https://www.amazon.com/Zero-One-Notes-Startups-Future/dp/0804139296" target="_blank" rel="noopener noreferrer">Peter Thiel\'s argument in Zero to One</a> is that every great business is built on a secret: something true that almost nobody else believes yet. The outside insider is the only position from which those secrets become consistently visible. Pure insiders have accepted the conventional wisdom and can no longer see what it conceals. Pure outsiders do not have the actual access. The outside insider holds both, which is why the contrarian bet that looks wrong from inside the game and invisible from outside it is, from that position, the most legible move available.' },
      { type: 'img', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Peter_Thiel_by_Dan_Taylor.jpg/960px-Peter_Thiel_by_Dan_Taylor.jpg', alt: 'Peter Thiel at a conference', caption: 'Peter Thiel, co-founder of PayPal and Palantir, author of Zero to One. Photo: Dan Taylor / Heisenberg Media / CC BY 2.0' },
      { type: 'p', html: 'Most founders and investors are optimizing inside the existing system. Competing for the same signals, the same markets, the same categories. The rulebook teaches that. It is fundamentally a zero-sum document: read it and you learn how to fight for your share of what already exists.' },
      { type: 'p', html: 'The outside insider sees something different. The game is not zero-sum. It never was. Business is not zero-sum. Leadership is not zero-sum. The person who wrote the rulebook was describing the table that existed at the time. The outside insider is building a different table entirely.' },
      { type: 'p', html: 'Bryan Kim, formerly of a16z, said in an interview that he optimizes for how fast he can say no. The Joy of Missing Out. When I first heard him articulate JOMO, I recognized something I had been trying to get to for a long time without having the vocabulary for it.' },
      { type: 'p', html: 'I say yes too often. I have always said yes too often. Overcommitted, overextended, watching the things that actually matter get crowded out by the things I agreed to because the anxiety of missing out felt more immediate than the cost of diluting my focus. And here is what that anxiety actually is: it is the insider trap. It is optimizing within the existing system, trying not to miss any of the existing opportunities, because the rulebook has trained you to believe the table is fixed and every empty seat is a permanent loss.' },
      { type: 'p', html: 'Every yes to the conventional opportunity is a no to the time required to find the unconventional one. JOMO is not passivity. It is the discipline of protecting the outside insider position. It is what you earn after you have played the game, learned its shape, and understood what it actually costs to keep saying yes.' },
      { type: 'p', html: 'I am still incredibly bad at this. Hopefully five years from now I am saying a hundred no\'s for every yes.' },
      { type: 'p', html: 'For me, this is a no I said early. Not just on high school founders, but on the broader convention that dismisses university students and young people who have not yet had the full traditional foundation. Everyone said it was too early. To a degree, that is true. But HTSI was built on that no. And the outlier signal is exactly what you find when you are willing to say it early enough, before the noise covers it. By the time the outlier is legible to everyone else, it is already priced in, trapped in a zero-sum race to split a consensus asset. This is how AI training works too: signal-to-noise degrades as more data arrives. The outside insider finds the signal when it is still clean, before the rulebook has caught up to it.' },
      { type: 'pull', text: 'Not every game is worth coming back to. The outside insider earns the judgment to know which ones are.' },
      { type: 'hr' },
      { type: 'h2', text: 'Why does this matter to you as a leader, founder, or investor?' },
      { type: 'p', html: 'The rulebook does not just teach you how to play the game. It teaches you that the game is zero-sum. That there is a fixed table and a finite number of seats and your job is to get one before someone else does. Most accelerator programs are built on this assumption. They hand founders the manual first: here is how to pitch, here is how to build a team, here is what a good deck looks like. By the time the founders start building, they are optimizing for the table that already exists.' },
      { type: 'callout', html: 'The outside insider sees that the table can be expanded. That is not an inspirational observation. It is a <strong>structural one</strong> that is only available from a position holding both the insider\'s access and the outsider\'s perspective simultaneously.' },
      { type: 'p', html: 'At HTSI, this is the question I think about most. The edge is not in the curriculum. It is in the sequence. Give someone the rulebook before they have played and you produce a skilled player of the game. Let someone play without it first, teach them the rules, then send them back, and you produce someone who understands the game at a level the rulebook was never designed to transmit.' },
      { type: 'p', html: 'Most accelerators get the sequence wrong.' },
      { type: 'h2', text: 'The final story is personal.' },
      { type: 'p', html: 'There have been rooms where I was the youngest person by over two decades, without the formal vocabulary, without the credential that explained why I was there. In most of those rooms, I produced and contributed nothing because I did not know enough to see what I was looking at or for.' },
      { type: 'p', html: 'In others, not knowing the rules was the most useful thing I had. The questions you ask because you did not know you were not supposed to ask them. The observation I made because I had not yet learned to write it off as obvious. The direction I pushed toward because I had not read the essay explaining why I was wrong. In that world, it did me quite good to stay stupid.' },
      { type: 'p', html: 'The outside insider position was not something I chose deliberately at first. It was circumstance: being younger, being on the startup side, not having the full manual. At some point it became a choice to maintain it. To keep going back to learn the rules without letting the architecture of the room become the limit of what you think is possible.' },
      { type: 'p', html: 'Try the game. Learn the game. Come back to the game.<br/><br/>Not once. Every time you leave and come back, the stakes rise and the rules shift underneath you.<br/><br/>That is what it means to be the ultimate outside insider.' },
    ],
    sources: [
      { label: 'Brian Armstrong on "action produces information" — Tim Ferriss Show', href: 'https://tim.blog/2021/03/08/brian-armstrong/' },
      { label: 'Paul Graham, "How to Think for Yourself"', href: 'https://paulgraham.com/think.html' },
      { label: 'Peter Thiel, Zero to One', href: 'https://www.amazon.com/Zero-One-Notes-Startups-Future/dp/0804139296' },
      { label: 'James Dyson on differentiation', href: 'https://en.wikipedia.org/wiki/James_Dyson' },
    ],
  },
];

export const CONTACT = [
  { k: 'Resonance', v: 'ethan@rsnc.ai', href: 'https://mail.google.com/mail/?view=cm&fs=1&to=ethan@rsnc.ai' },
  { k: 'Research', v: 'ethan-yip@substrate-labs.org', href: 'https://mail.google.com/mail/?view=cm&fs=1&to=ethan-yip@substrate-labs.org' },
  { k: 'LinkedIn', v: '/in/yip-ethan', href: 'https://www.linkedin.com/in/yip-ethan' },
];

export const LINKS = {
  email: 'ethan@rsnc.ai',
  linkedin: 'https://www.linkedin.com/in/yip-ethan',
  resonance: 'https://rsnc.ai',
  research: 'https://substrate-labs.org',
};
